name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: getVersion
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set publish tag
        id: publishVars
        run: echo ::set-output name=TAG::${{ contains(steps.getVersion.outputs.VERSION, '-') && 'next' || 'latest' }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          npm install
          npm run build
      - name: Publish
        run: npm publish --tag=${{ steps.publishVars.outputs.TAG }} --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: dist
